#
# 应用端口
# 启动多个实例时，可 --server.port=xxxx 重新指定端口
#
server:
  port: 9204

#
# 为 spring-boot-starter-actuator 配置
# 解决 /refresh 时，报错 401 Unauthorized,Full authentication is required to access this resource.
# 忽略权限拦截
#
management:
  security:
    enabled: false

#
# rabbmit配置
#
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: springclouddemo
    password: springclouddemo

##################  以下是测试内容 ###################

foo: keep foolish keep hungery
tools:
  name: 2018 tools gogogo
  abf:
    url: http://localhost:9300/abf

jdbc:
  mysql:
    url: jdbc:mysql://localhost:3306/sampledb
    username: root
    password: 123456

